### ISSUE TITLE
Разве на лекциях говорилось о том, что нужно использовать remove?

### ISSUE THREAD

**Issue by coursar** [Shohin217/purchases#5]
https://github.com/Shohin217/purchases/blob/28cfc761fbcdaf5086c92c347cb777176e9f3124/src/js/main.js#L44

**Comment by Shohin217** [comment]
f23ff3bc5a17587ab82e584ce96ee3cb23247ec7

**Comment by Shohin217** [comment]
7ba224d0a557c2ae9d68df32cc25b8f535599e34
